<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-52GUJ27" failures="2" tests="2" name="Default test(failed)" time="0.222" errors="0" timestamp="2022-06-14T20:27:04 IST">
  <testcase classname="xml_study.Study5" name="Test1" time="0.034">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at xml_study.Study5.Test1(Study5.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="xml_study.Study5" name="Test3" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at xml_study.Study5.Test3(Study5.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="xml_study.Study5" name="Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase classname="xml_study.Study5" name="Test4" time="0.0">
    <ignored/>
  </testcase> <!-- Test4 -->
</testsuite> <!-- Default test(failed) -->
